---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-egress-ysksuzuki-com-v1beta1-egress
  failurePolicy: Fail
  name: megress.kb.io
  rules:
  - apiGroups:
    - egress.ysksuzuki.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - egresses
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-egress-ysksuzuki-com-v1beta1-egress
  failurePolicy: Fail
  name: vegress.kb.io
  rules:
  - apiGroups:
    - egress.ysksuzuki.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - egresses
  sideEffects: None
